name: Package Agent for Download

on:
  push:
    branches:
      - mul
    paths:
      - 'agent.py'
      - 'start_agent.bat'
      - 'install_python.bat'
      - 'AGENT_README.txt'
      - 'Netzlab.ico'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create agent package directory
      run: mkdir -p agent_package

    - name: Copy agent files
      run: |
        cp agent.py agent_package/
        cp start_agent.bat agent_package/
        cp install_python.bat agent_package/
        cp AGENT_README.txt agent_package/README.txt
        cp Netzlab.ico agent_package/

    - name: Create ZIP file
      run: |
        cd agent_package
        zip -r ../SACMES_Agent.zip .
        cd ..

    - name: Ensure static/downloads directory exists
      run: mkdir -p static/downloads

    - name: Move ZIP to downloads
      run: mv SACMES_Agent.zip static/downloads/

    - name: Commit and push ZIP file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add static/downloads/SACMES_Agent.zip
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-package agent for download" && git push)
